Fri Oct 22 10:53:26 PDT 1999 (Mandrake)
removed almost all the warnings.
except for:
main.c:287: warning: implicit declaration of function `__imlib_draw_line'
which I believe is because it's not using the appropriate API call yet.


git-svn-id: http://svn.enlightenment.org/svn/e/trunk/e17/libs/imlib2@945 7cbeb6ba-43b4-40fd-8cce-4c39aea84d33